stages:
  - build
  - deploy

variables:
  NPM_MIZ_REGISTRY_INSTALL: https://gitlab.com/api/v4/projects/34284421/packages/npm/

build:
  image: node:latest    # Run the job in a `node` docker image
  stage: build
  script:
    - npm config set @university-of-missouri:registry "${NPM_MIZ_REGISTRY_INSTALL}"
    - npm config set -- '//gitlab.com/api/v4/projects/34284421/packages/npm/:_authToken' "${MIZ_DS_ACCESS_TOKEN}"
    # - npm config set always-auth true
    - yarn install      # Run `yarn install` and `yarn build`
    - yarn build
  artifacts:
    paths:
      - build/          # Save the build result as an artfact

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public         
  artifacts:
    paths:
      - public